--Credits to (https://genshin.honeyhunterworld.com/) for the Data
CREATE TABLE Weapons (
    id BIGSERIAL PRIMARY KEY,
    Name VARCHAR(60),
    Star INTEGER,
    WeaponType_ID INT REFERENCES WeaponTypes(id),
    SecondStats_ID INT REFERENCES SecondStats(id),
    WeaponDomain_ID INT REFERENCES AscensionDomains(id),
    WeaponDomainMaterials_ID INT REFERENCES SkillDomainMaterials(id),
    EnhancementMat1ID INT REFERENCES EnhancementMatSet(id),
    EnhancementMat2ID INT REFERENCES EnhancementMatSet(id),
    Availabilties INT REFERENCES Availability(id),
    ImgURL VARCHAR(50)
);

INSERT INTO Weapons (
    Name,
    Star, 
    WeaponType_ID,
    SecondStats_ID,
    WeaponDomain_ID, 
    WeaponDomainMaterials_ID, 
    EnhancementMat1ID, 
    EnhancementMat2ID,   
    Availabilties, 
    ImgURL
    ) 
VALUES 
--Name                                 Str  Wt 2S W Wm E1 E2 A  url
--3 Stars Sword   
('Dark Iron Sword',                      3, 1, 6, 4, 4,12, 3, 1, 'BlackIronSword.png'),
('Cool Steel',                           3, 1, 1, 2, 1, 5, 4, 1, 'CoolSteel.png'),
('Harbinger of Dawn',                    3, 1, 7, 2, 2, 8, 1, 2, 'HarbingerOfDawn.png'),
('Traveler''s Handy Sword',              3, 1, 3, 2, 3,15, 6, 3, 'TravelersHandySword.png'),
('Fillet Blade',                         3, 1, 1, 4, 5,13,19, 2, 'FilletBlade.png'), 
('Skyrider Sword',                       3, 1, 5, 4, 6,23,11, 3, 'SkyriderSword.png'),
--3 Stars Claymore  
('Ferrous Shadow',                       3, 2, 2, 2, 1, 5,22, 1, 'FerrousShadow.png'),
('Bloodstained Greatsword',              3, 2, 6, 2, 2, 4, 8, 2, 'BloodtaintedGreatsword.png'),
('White Iron Greatsword',                3, 2, 3, 2, 3,15, 1, 3, 'WhiteIronGreatsword.png'),
('Debate Club',                          3, 2, 1, 4, 5, 3,13, 2, 'DebateClub.png'),
('Skyrider Greatsword',                  3, 2, 4, 4, 6,23,19, 3, 'SkyriderGreatsword.png'),
--3 Stars Polearm   
('White Tassel',                         3, 3, 8, 4, 4,12,11, 1, 'WhiteTassel.png'),
('Halberd',                              3, 3, 1, 4, 5,13,22, 2, 'Halberd.png'),
('Black Tassel',                         3, 3, 2, 4, 6, 4,23, 3, 'BlackTassel.png'),
--3 Stars Catalyst   
('Magic Guide',                          3, 4, 6, 2, 1, 5, 1, 1, 'MagicGuide.png'),
('Thrilling Tales of Dragon Slayers',    3, 4, 2, 2, 2, 8, 6, 2, 'ThrillingTalesOfDragonSlayers.png'),
('Otherwordly Story',                    3, 4, 5, 2, 3,15, 3, 3, 'OtherworldlyStory.png'),                 
('Emerald Orb',                          3, 4, 6, 4, 4,12,19, 1, 'EmeraldOrb.png'),
('Twin Nepherite',                       3, 4, 8, 4, 5,13,11, 2, 'TwinNephrite.png'),
--3 Stars Bow 
('Raven Bow',                            3, 5, 6, 2, 1, 4, 5, 1, 'RavenBow.png'),
('Sharpshooter''s Oath',                 3, 5, 7, 2, 2, 8, 1, 2, 'SharpshootersOath.png'),
('Recurve Bow',                          3, 5, 2, 2, 3,15, 6, 3, 'RecurveBow.png'),
('Slingshot',                            3, 5, 8, 4, 4, 3,12, 1, 'Slingshot.png'),
('Messenger',                            3, 5, 7, 4, 5,13,19, 2, 'Messenger.png'),
--4 Stars Sword  
('Favonius Sword',                       4, 1, 5, 2, 1, 4, 5, 1, 'FavoniusSword.png'),
('The Flute',                            4, 1, 1, 2, 2, 8, 1, 2, 'TheFlute.png'),
('Sacrificial Sword',                    4, 1, 5, 2, 3,15, 6, 3, 'SacrificialSword.png'),
('Royal Longsword',                      4, 1, 1, 2, 1, 3, 5, 1, 'RoyalLongsword.png'),
('Lion''s Roar',                         4, 1, 1, 4, 4,12,19, 1, 'LionsRoar.png'),
('Prototype Rancour',                    4, 1, 4, 4, 5,13,11, 2, 'PrototypeRancour.png'),
('Iron Sting',                           4, 1, 6, 4, 6,23,22, 3, 'IronSting.png'),
('Blackcliff Longsword',                 4, 1, 7, 4, 4, 4,12, 1, 'BlackcliffLongsword.png'),
('The Black Sword',                      4, 1, 8, 2, 2, 8, 1, 2, 'TheBlackSword.png'),
('Sword of Descension',                  4, 1, 1, 2, 2, 8,19, 2, 'SwordOfDescension.png'),
('Festering Desire',                     4, 1, 5, 2, 3,11, 5, 3, 'Festering Desire.png'),
('The Alley Flash',                      4, 1, 6, 2, 1, 6, 5, 1, 'TheAlleyFlash.png'),
('Amenoma Kageuchi',                     4, 1, 1, 6, 7,20,16, 1, 'AmenomaKageuchi.png'),
('Cinnabar Spindle',                     4, 1, 3, 2, 1,15, 3, 1, 'CinnabarSpindle.png'),
('Kagotsurube Isshin',                   4, 1, 1, 6, 9, 9, 2, 3, 'KagotsurubeIsshin.png'),
('Sapwood Blade',                        4, 1, 5, 8,10,17,21, 1, 'SapwoodBlade.png'),
('Xiphos'' Moonlight',                   4, 1, 5, 8,10,21,18, 1, 'XiphosMoonlight.png'),
('Toukabou Shigure',                     4, 1, 6, 6, 8,20,18, 2, 'ToukabouShigure.png'),
('Wolf-Fang',                            4, 1, 8, 2, 1,15, 3, 1, 'Wolf-Fang.png'),
('Finale of the Deep',                   4, 1, 1,10,14,20,27, 2, 'FinaleOfTheDeep.png'),
('Fleuve Cendre Ferryman',               4, 1, 5,10,13,27,31, 1, 'FleuveCendreFerryman.png'),
('The Dockhand''s Assistant',            4, 1, 2,10,14,31,29, 2, 'The DockhandsAssistant.png'),
('Sword of Narzissenkreuz',              4, 1, 1,10,13,31,29, 1, 'SwordOfNarzissenkreuz.png'),
--4 Stars Claymore   
('Favonious Greatsword',                 4, 2, 6, 8, 3,15,11, 3, 'FavoniousGreatsword.png'),
('The Bell',                             4, 2, 2, 2, 1,22, 5, 1, 'TheBell.png'),
('Sacrifical Greatsword',                4, 2, 5, 2, 2, 4, 8, 2, 'SacrificialGreatsword.png'),
('Royal Greatsword',                     4, 2, 1, 2, 3,15, 1, 3, 'RoyalGreatsword.png'),
('Rainslasher',                          4, 2, 6, 4, 5, 6,13, 2, 'Rainslasher.png'),
('Prototype Archaic',                    4, 2, 1, 4, 6, 3,23, 3, 'PrototypeArchaic.png'),
('Whiteblind',                           4, 2, 3, 4, 4,12,19, 1, 'Whiteblind.png'),
('Blackcliff Slasher',                   4, 2, 7, 4, 5,13,11, 2, 'BlackcliffSlasher.png'),
('Serpent Spine',                        4, 2, 8, 4, 6,23,22, 3, 'SerpentSpine.png'),
('Snow-Tombed Starsilver',               4, 2, 4, 2, 1, 1, 5, 1, 'Snow-TombedStarsilver.png'),
('Lithic Blade',                         4, 2, 1, 4, 4, 4,12, 1, 'LithicBlade.png'),
('Katsuragikiri Nagamasa',               4, 2, 5, 6, 8,20,16, 2, 'KatsuragikiriNagamasa.png'),
('Luxurious Sea-Lord',                   4, 2, 1, 4, 6,23, 1, 3, 'LuxuriousSea-Lord.png'),
('Akuoumaru',                            4, 2, 1, 6, 7,20,10, 1, 'Akuoumaru.png'),
('Forest Regalia',                       4, 2, 5, 8,10,17,21, 1, 'ForestRegalia.png'),
('Makhaira Aquamarine',                  4, 2, 6, 8,12,19,17, 3, 'MakhairaAquamarine.png'),
('Mailed Flower',                        4, 2, 6, 2, 3, 2,26, 3, 'MailedFlower.png'),
('Talking Stick',                        4, 2, 8,10,11,26, 1, 2, 'TalkingStick.png'),
('Tidal Shadow',                         4, 2, 1,10,15,28,30, 3, 'TidalShadow.png'),
('Portable Power Saw',                   4, 2, 2,10,15,28,30, 3, 'PortablePowerSaw.png'),
--4 Stars Polearm  
('Dragon''s Bane',                       4, 3, 6, 4, 5, 6,13, 2, 'DragonsBane.png'),
('Prototype Starglitter',                4, 3, 5, 4, 6, 3,23, 3, 'PrototypeStarglitter.png'),
('Crescent Pike',                        4, 3, 4, 4, 4,12,19, 1, 'CrescentPike.png'),
('Blackcliff Pole',                      4, 3, 7, 4, 5,13,11, 2, 'BlackcliffPole.png'),
('Deathmatch',                           4, 3, 8, 2, 2,22, 8, 2, 'Deathmatch.png'),
('Favonius Lance',                       4, 3, 5, 2, 3,15, 1, 3, 'FavoniusLance.png'),
('Royal Spear',                          4, 3, 1, 4, 5,13,11, 2, 'RoyalSpear.png'),
('Dragonspine Spear',                    4, 3, 4, 2, 2,13,11, 2, 'DragonspineSpear.png'),
('Lithic Spear',                         4, 3, 1, 4, 6, 4,23, 3, 'LithicSpear.png'),
('Kitain Cross Spear',                   4, 3, 6, 6, 9,19,16, 3, 'KitainCrossSpear.png'),
('The Catch',                            4, 3, 5, 6, 9,16, 2, 3, 'TheCatch.png'),
('Wavebreaker''s Fin',                   4, 3, 1, 6, 9,20,10, 3, 'WavebreakersFin.png'),
('Moonpiercer',                          4, 3, 6, 8,11,11,17, 2, 'WavebreakersFin.png'),
('Missive Windspear',                    4, 3, 1, 2, 2, 9, 1, 2, 'Moonpiercer.png'),
('Ballad of the Fjords',                 4, 3, 8,10,15,22, 7, 3, 'BalladOfTheFjords.png'),
('Rightful Reward',                      4, 3, 2,10,15,28,28, 3, 'RightfulReward.png'),
('Prospector''s Drill',                  4, 3, 1,10,13,29,30, 1, 'ProspectorsDrill.png'),
-- 4 Stars Catalyst  
('Favonius Codex',                       4, 4, 5, 2, 1, 6, 5, 1, 'FavoniusCodex.png'),
('The Wisdith',                          4, 4, 7, 2, 2, 3, 8, 2, 'TheWidsith.png'),
('Sacrificial Fragments',                4, 4, 5, 2, 3,15,19, 3, 'SacrificialFragments.png'),
('Royal Grimoire',                       4, 4, 1, 2, 1,11, 5, 1, 'RoyalGrimoire.png'),
('Solar Pearl',                          4, 4, 8, 4, 4,12,22, 1, 'SolarPearl.png'),
('Prototype Amber',                      4, 4, 2, 4, 5, 4,13, 2, 'PrototypeAmber.png'),
('Mappa Mare',                           4, 4, 6, 4, 6,23, 1, 3, 'MappaMare.png'),
('Blackcliff Agate',                     4, 4, 7, 4, 4, 6,12, 1, 'BlackcliffAgate.png'),
('Eye of Perception',                    4, 4, 1, 4, 5, 3,13, 2, 'EyeOfPerception.png'),
('Frostbearer',                          4, 4, 1, 2, 3,15,22, 3, 'Frostbearer.png'),
('Dodoco Tales',                         4, 4, 1, 2, 2, 3, 8, 2, 'DodocoTales.png'),
('Wine and Song',                        4, 4, 5, 2, 2,19, 8, 2, 'WineAndSong.png'),
('Hakushin Ring',                        4, 4, 5, 6, 7, 6,14, 1, 'HakushinRing.png'),
('Oathsworn Eye',                        4, 4, 1, 6, 7, 2,10, 1, 'OathswornEye.png'),
('Fruit of Fulfillment',                 4, 4, 5, 8,11, 9,24, 2, 'FruitOfFulfillment.png'),
('Wandering Evenstar',                   4, 4, 6, 8,11,24,25, 2, 'WanderingEvenstar.png'),
('Sacrificial Jade',                     4, 4, 7, 4, 4, 6,13, 1, 'SacrificialJade.png'),
('Flowing Purity',                       4, 4, 1,10,14,31,28, 2, 'FlowingPurity.png'),
('Ballad of the Boundless Blue',         4, 4, 5, 1, 2,19,23, 2, 'BalladOfTheBoundlessBlue.png'),
--4 Stars Bow  
('Favonius Warbow',                      4, 5, 5, 2, 3,15,22, 3, 'FavoniusWarbow.png'),
('The Stringless',                       4, 5, 6, 2, 1, 4, 5, 1, 'TheStringless.png'),
('Sacrificial Bow',                      4, 5, 5, 2, 2, 1, 8, 2, 'SacrificialBow.png'),
('Royal Bow',                            4, 5, 1, 2, 3,15, 6, 3, 'RoyalBow.png'),
('Rust',                                 4, 5, 1, 4, 4, 3,12, 1, 'Rust.png'),
('Prototype Cresecent',                  4, 5, 1, 4, 5,13,19, 2, 'PrototypeCrescent.png'),
('Compound Bow',                         4, 5, 4, 4, 6,11,23, 3, 'CompoundBow.png'),
('Blackcliff Warbow',                    4, 5, 7, 4, 4,12,22, 1, 'BlackcliffWarbow.png'),
('The Viridescent Hunt',                 4, 5, 8, 2, 1, 4, 5, 1, 'TheViridescentHunt.png'),
('Windblume Ode',                        4, 5, 6, 2, 3,22, 8, 3, 'WindblumeOde.png'),
('Alley Hunter',                         4, 5, 1, 2, 3,15, 1, 3, 'AlleyHunter.png'),
('Mitternachts Waltz',                   4, 5, 4, 2, 1,19, 5, 1, 'MitternachtsWaltz.png'),
('Hamayumi',                             4, 5, 1, 6, 8, 4,14, 2, 'Hamayumi.png'),
('Predator',                             4, 5, 1, 6, 8, 4,14, 2, 'Predator.png'),
('Mouun''s Moon',                        4, 5, 1, 6, 8, 2,14, 2, 'MouunsMoon.png'),
('Fading Twilight',                      4, 5, 5, 4, 6, 6,12, 3, 'FadingTwilight.png'),
('King''s Squire',                       4, 5, 1, 8,12, 4,25, 3, 'KingsSquire.png'),
('End of the Line',                      4, 5, 5, 8,12,24,25, 3, 'EndOfTheLine.png'),
('Ibis Piercer',                         4, 5, 1, 8,10,21, 7, 1, 'IbisPiercer.png'),
('Scion of the Blazing Sun',             4, 5, 8, 8,12, 7,24, 3, 'ScionOfTheBlazingSun.png'),
('Song of Stillness',                    4, 5, 1,10,13, 4,27, 1, 'SongOfStillness.png'),
('Range Gauge',                          4, 5, 1,10,13,27,31, 1, 'RangeGauge.png'),
--5 Stars Sword  
('Aquila Favonia',                       5, 1, 4, 2, 1, 4, 5, 1, 'AquilaFavonia.png'),
('Skyward Blade',                        5, 1, 5, 2, 2, 1, 8, 2, 'SkywardBlade.png'),
('Summit Shaper',                        5, 1, 1, 4, 4, 3,12, 1, 'SummitShaper.png'),
('Primordial Jade Cutter',               5, 1, 8, 4, 5,13,19, 2, 'PrimordialJadeCutter.png'),
('Freedom-Sworn',                        5, 1, 6, 2, 3,15, 6, 3, 'Freedom-Sworn.png'),
('Mistsplitter Reforged',                5, 1, 7, 6, 7,20,16, 1, 'MistsplitterReforged.png'),
('Haran Geppaku Futsu',                  5, 1, 8, 6, 8,20, 9, 2, 'HaranGeppakuFutsu.png'),
('Key of Khaj-Nisut',                    5, 1, 2, 8,10,21,18, 1, 'KeyOfKhaj-Nisut.png'),
('Light of Foliar Incision',             5, 1, 8, 8,10,21,26, 1, 'LightOfFoliarIncision.png'),
('Splendor of Tranquil Waters',          5, 1, 7,10,14,27,31, 2, 'SplendorOfTranquilWaters.png'),
--5 Stars Claymore   
('Skyward Pride',                        5, 2, 5, 2, 2, 1, 8, 2, 'SkywardPride.png'),
('Wolf''s Gravestone',                   5, 2, 1, 2, 3,15, 6, 3, 'WolfsGravestone.png'),
('The Unforged',                         5, 2, 1, 4, 5,13,19, 2, 'TheUnforged.png'),
('Song of Broken Pines',                 5, 2, 4, 2, 1, 3, 5, 1, 'SongOfBrokenPines.png'),
('Redhorn Stonethresher',                5, 2, 7, 6, 8,20,10, 2, 'RedhornStonethresher.png'),
('Beacon of the Reed Sea',               5, 2, 7, 8,12,21,26, 3, 'BeaconOfTheReedSea.png'),
--5 Stars Polearm   
('Vortex Vanguisher',                    5, 3, 1, 4, 6,19,23, 3, 'VortexVanquisher.png'),
('Primordial Jade Winged-Spear',         5, 3, 8, 4, 4,12,11, 1, 'PrimordialJadeWinged-Spear.png'),
('Skyward Spine',                        5, 3, 5, 2, 3,15, 6, 3, 'SkywardSpine.png'),
('Staff of Homa',                        5, 3, 7, 4, 6, 1, 8, 3, 'StaffOfHoma.png'),
('Engulfing Lighting',                   5, 3, 5, 6, 9,20,16, 3, 'EngulfingLightning.png'),
('Calamity Queller',                     5, 3, 1, 4, 5,13,22, 2, 'CalamityQueller.png'),
('Staff of the Scarlet Sands',           5, 3, 8, 8,11,17,24, 2, 'StaffOfTheScarletSands.png'),
--5 Stars Catalyst   
('Lost Prayer to the Sacred Winds',      5, 4, 8, 2, 3,15, 1, 3, 'LostPrayerToTheSacredWinds.png'),
('Skyward Atlas',                        5, 4, 1, 2, 2, 4, 8, 2, 'SkywardAtlas.png'),
('Memory of Dust',                       5, 4, 1, 4, 6, 3,23, 3, 'MemoryOfDust.png'),
('Everlasting Moonglow',                 5, 4, 2, 6, 7, 2,14, 1, 'EverlastingMoonglow.png'),
('Kagura''s Verity',                     5, 4, 7, 6, 9, 2,10, 3, 'KagurasVerity.png'),
('A Thousand Floating Dreams',           5, 4, 5, 8,11,18,24, 2, 'AThousandFloatingDreams.png'),
('Tulaytullah''s Remembrance',           5, 4, 7, 8,12,24,25, 3, 'TulaytullahsRemembrance.png'),
('Jadefall''s Splendor',                 5, 4, 2 , 4, 4, 7,24, 1, 'JadefallsSplendor.png'),
('Tome of the Eternal Flow',             5, 4, 7,10,14,28,30, 2, 'TomeOfTheEternalFlow.png'),
('Cashflow Supervision',                 5, 4, 8,10,15,31,29, 3, 'CashflowSupervision.png'),
--5 Stars Bow   
('Skyward Harp',                         5, 5, 8, 2, 2, 4, 8, 2, 'SkywardHarp.png'),
('Amo''s Bow',                           5, 5, 1, 2, 3,15, 1, 3, 'AmosBow.png'),
('Elegy For The End',                    5, 5, 5, 2, 2,11, 5, 2, 'ElegyForTheEnd.png'),
('Thundering Pulse',                     5, 5, 7, 6, 8, 4,14, 2, 'ThunderingPulse.png'),
('Polar Star',                           5, 5, 8, 6, 9, 2,10, 3, 'PolarStar.png'),
('Aqua Simulacra ',                      5, 5, 7, 4, 4, 9, 2, 1, 'AquaSimulacra.png'),
('Hunter''s Path',                       5, 5, 8, 8,12,21,25, 3, 'HuntersPath.png'),
('The First Great Magic',                5, 5, 7,10,13,27,31, 1, 'TheFirstGreatMagic.png')
;   
-- DEVNOTE: Add these Correction to new Table (Find the Weapons themselves Unfortunately)
--UPDATE weapons SET domain_id = 2 WHERE id = 115 ;   
--UPDATE weapons SET domain_id = 4 WHERE id = 13 ;  
--UPDATE weapons SET domain_id = 4 WHERE id = 61 ;  

SELECT * FROM allWeapons;
CREATE VIEW allWeapons AS 
SELECT 
    weapons.id,
    weapons.name,
    weapons.star,
    wt.type,
    ss.stat,
    sd.DomainName,
    STRING_TO_ARRAY(CONCAT(wm.Material2, ',', wm.Material3, ',', wm.Material4, ',', wm.Material5), ',') as WeaponMats,
    STRING_TO_ARRAY(CONCAT(em.Mat1, ',', em.Mat2, ',', em.Mat3), ',') as EnhanceMats1,
    STRING_TO_ARRAY(CONCAT(em2.Mat1, ',', em2.Mat2, ',', em2.Mat3), ',') as EnhanceMats2,
    Availability.days,
    Weapons.ImgURL
FROM weapons
LEFT JOIN WeaponTypes AS wt ON Weapons.WeaponType_ID = wt.id
LEFT JOIN SecondStats as ss ON Weapons.SecondStats_ID = ss.id
LEFT JOIN AscensionDomains as sd ON Weapons.WeaponDomain_ID = sd.id
LEFT JOIN WMaterialSet as wm ON Weapons.WeaponDomainMaterials_ID = wm.id
LEFT JOIN allMobLootSets as em on Weapons.EnhancementMat1ID = em.id
LEFT JOIN allMobLootSets as em2 on Weapons.EnhancementMat2ID = em2.id
LEFT JOIN Availability on Weapons.Availabilties = Availability.id 
;